# PySNMP SMI module. Autogenerated from smidump -f python FMANALYSER-MIB
# by libsmi2pysnmp-0.1.3 at Fri Apr 27 23:37:32 2012,
# Python version (2, 6, 7, 'final', 0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, ModuleIdentity, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, enterprises, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "enterprises")

# Objects

gaftech = MibIdentifier((1, 3, 6, 1, 4, 1, 999999))
fmanalyser = ModuleIdentity((1, 3, 6, 1, 4, 1, 999999, 1)).setRevisions(("1912-04-27 21:37",))
if mibBuilder.loadTexts: fmanalyser.setOrganization("Gaftech")
if mibBuilder.loadTexts: fmanalyser.setContactInfo("gabriel@gaftech.fr")
if mibBuilder.loadTexts: fmanalyser.setDescription("The MIB module for fmanalyser snmp plugin")
software = MibIdentifier((1, 3, 6, 1, 4, 1, 999999, 1, 1))
softVersion = MibScalar((1, 3, 6, 1, 4, 1, 999999, 1, 1, 0), OctetString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: softVersion.setDescription("fmanalyser software version")
device = MibIdentifier((1, 3, 6, 1, 4, 1, 999999, 1, 2))
online = MibScalar((1, 3, 6, 1, 4, 1, 999999, 1, 2, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 1))).setMaxAccess("readonly")
if mibBuilder.loadTexts: online.setDescription("The device online/offline status.")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("FMANALYSER-MIB", PYSNMP_MODULE_ID=fmanalyser)

# Objects
mibBuilder.exportSymbols("FMANALYSER-MIB", gaftech=gaftech, fmanalyser=fmanalyser, software=software, softVersion=softVersion, device=device, online=online)

